spring:
  datasource:
    url: jdbc:mysql://IP_Address:3306/nomad
    username: root
    password: password
mybatis-plus:
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: REUSE
    use-actual-param-name: true

springdoc:
  swagger-ui:
    path: /doc/swagger-ui
  api-docs:
    path: /api-docs

image:
  path: /home/image_path
